#!/bin/sh
### BEGIN INIT INFO
# Provides:          hexo
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hexo Service
# Description:       This script manages the Hexo service.
### END INIT INFO

# Change the following values to match your setup
HEXO_DIR=/hexo    # Path to your Hexo installation directory
NODE_BIN=/usr/bin/node    # Path to the Node.js executable

PID_FILE=/var/run/hexo.pid

case "$1" in
    start)
        if [ -f $PID_FILE ]; then
            echo "Hexo is already running."
            exit 1
        fi

        echo "Starting Hexo"
        cd $HEXO_DIR
        npm install
        hexo clean
        hexo generate
        nohup hexo serve 2>&1 >> /var/log/hexo-serve.log
        echo $! > $PID_FILE
        ;; 
    stop)
        if [ ! -f $PID_FILE ]; then
            echo "Hexo is not running."
            exit 1
        fi

        echo "Stopping Hexo"
        kill $(cat $PID_FILE)
        rm -f $PID_FILE
        ;;
    restart)
        echo "Restarting Hexo"
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
